import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container': '#f0eded',
        'on-secondary-fixed-variant': '#474746',
        'inverse-primary': '#ffb1c3',
        'background': '#fcf9f8',
        'outline-variant': '#e5bcc4',
        'on-tertiary-fixed-variant': '#8a0556',
        'surface-tint': '#03C75A',
        'surface-bright': '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'primary': { DEFAULT: '#03C75A', foreground: '#ffffff' },
        'primary-fixed': '#ffd9e0',
        'on-error-container': '#93000a',
        'secondary-fixed': '#e5e2e1',
        'tertiary-fixed-dim': '#ffb0cf',
        'on-tertiary-fixed': '#3d0023',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffd8e5',
        'surface-variant': '#e5e2e1',
        'surface-container-low': '#f6f3f2',
        'tertiary-container': '#c74186',
        'surface': '#fcf9f8',
        'on-secondary-container': '#636262',
        'error': '#ba1a1a',
        'surface-container-high': '#eae7e7',
        'on-error': '#ffffff',
        'inverse-surface': '#313030',
        'surface-container-highest': '#e5e2e1',
        'tertiary': '#a7266c',
        'on-background': '#1c1b1b',
        'outline': '#906e75',
        'primary-fixed-dim': '#ffb1c3',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'secondary': '#5f5e5e',
        'secondary-fixed-dim': '#c8c6c5',
        'primary-container': '#03C75A',
        'on-primary-container': '#fffbff',
        'on-surface': '#1c1b1b',
        'on-primary-fixed': '#3f0019',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f3f0ef',
        'on-secondary-fixed': '#1b1c1c',
        'on-primary-fixed-variant': '#8f0041',
        'secondary-container': '#e2dfde',
        'on-surface-variant': '#5c3f45',
        'error-container': '#ffdad6',
        'vuka-pink': '#03C75A',
        // ShadCN tokens (referenced by installed components)
        'border': 'var(--border)',
        'input': 'var(--input)',
        'ring': 'var(--ring)',
        'foreground': 'var(--foreground)',
        'muted': {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        'accent': {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        'destructive': {
          DEFAULT: 'var(--destructive)',
        },
      },
      fontFamily: {
        headline: ['var(--font-plus-jakarta)', 'var(--font-noto-sans-kr)', 'sans-serif'],
        body: ['var(--font-plus-jakarta)', 'var(--font-noto-sans-kr)', 'sans-serif'],
        label: ['var(--font-plus-jakarta)', 'var(--font-noto-sans-kr)', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

export default config
